steps:
  - name: 'node:20'
    dir: 'frontend'
    entrypoint: npm
    args: ['install']

  - name: 'node:20'
    dir: 'frontend'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - 'gsutil -m rsync -r frontend/dist gs://smart-retail-app-data'

options:
  logging: CLOUD_LOGGING_ONLY