steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud functions deploy order-api \
          --gen2 \
          --runtime=python311 \
          --region=asia-south1 \
          --source=order-api \
          --entry-point=publish_order \
          --trigger-http \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY