name: Deploy Forecast API

on:
  push:
    branches:
      - main
    paths:
      - 'forecast-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: forecast-api

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud run deploy forecast-api \
            --source=. \
            --region=asia-south1 \
            --allow-unauthenticated
